site_name: The King Crab site
site_url: https://kingcrab.github.io/
site_author: JasonYoung
site_description: >-
  The King Crab site is a place to learn about the.
  King Crab.

theme:
  name: material